# Resources settings
source:      .
layouts:     ./_layouts
timezone:    +0800
lang: zh-CN
gems: ['jekyll-paginate', 'jekyll-multiple-languages']
languages: ['cn', 'en']
language_default: 'en'

# Site settings
email: 1540294142@qq.com
author: Joytou Wu
url: https://joytou.github.io

github: https://github.com/joytou/
baseurl: ""

future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
paginate_path: "/:lang/page:num"
paginate: 2
markdown: kramdown
excerpt_separator: '<!-- more -->'

exclude: ['README.md']

github_username: joytou
owner_name: Joytou

# Keywords
keywords:
        - "github"
        - "bootstrap"
        - "blog"
        - "joytou"
        - "markdown"
        - "博客"
        - "个人博客"
        - "博客模板"
        
#Others
BaiduSiteVerification: "lLhmCmVmTf"
